#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include "rld.h"

static const char LogTable256[256] = {
#define LT(n) n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n
    -1, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
    LT(4), LT(5), LT(5), LT(6), LT(6), LT(6), LT(6),
    LT(7), LT(7), LT(7), LT(7), LT(7), LT(7), LT(7), LT(7)
};

// this table is generated by rld_gen_ddec_table() below
static int16_t ddec_table[256] = {
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 249, 265, 281, 297, 313, 329, 345, 361, 377, 393, 409, 425, 441, 457, 473, 489,
     119, 119, 119, 119, 135, 135, 135, 135, 151, 151, 151, 151, 167, 167, 167, 167, 183, 183, 183, 183, 199, 199, 199, 199, 215, 215, 215, 215, 231, 231, 231, 231,
      -9,  -9, -10, -10, -11, -11, -12, -12, -13, -13, -14, -14, -15, -15, -16, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31, -32,
      85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
      -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,
      -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,
      -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,
      -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8
};

static inline int ilog2(uint32_t v)
{
	register uint32_t t, tt;
	if ((tt = (v >> 16))) return (t = (tt >> 8)) ? 24 + LogTable256[t] : 16 + LogTable256[tt];
	return (t = (v >> 8)) ? 8 + LogTable256[t] : LogTable256[v];
}

inline uint32_t rld_delta_enc1(uint32_t x, int *width)
{
	int y = ilog2(x);
	int z = ilog2(y + 1);
	*width = (z<<1) + 1 + y;
	return (x^(1<<y)) | (y+1)<<y;
}

void rld_gen_ddec_table()
{
	int i, j, w;
	for (i = 1; i < 32; ++i) { // traverse gamma codes up to 9 bits
		w = (ilog2(i)<<1) + 1;
		for (j = 0; j < 1<<(9-w); ++j)
			ddec_table[i<<(9-w)|j] = (i-1)<<4 | w; // i-1 because the highest bit is removed
	}
	for (i = 2; i < 32; ++i) { // traverse delta codes up to 9 bits
		uint32_t x = rld_delta_enc1(i, &w);
		for (j = 0; j < 1<<(9-w); ++j)
			ddec_table[x<<(9-w)|j] = ~i;
	}
	ddec_table[0] = 0;
	for (i = 0; i < 8; ++i) {
		printf("    ");
		for (j = 0; j < 32; ++j) printf("%4d,", ddec_table[i*32+j]);
		putchar('\n');
	}
}

inline int rld_delta_dec1(uint64_t x)
{
	int z;
	if (x>>63) return 1;
	z = ddec_table[x>>55];
	if (z > 0) {
		int a = z>>4;
		return x<<(z&0xf)>>(64-a)|1u<<a;
	} else if (z < 0) return ~z;
	return 0;
}

rldenc_t *rld_enc_init(int asize, int bbits)
{
	rldenc_t *e;
	e = calloc(1, sizeof(rldenc_t));
	e->z = malloc(sizeof(void*));
	e->z[0] = calloc(RLD_SUPBLK_SIZE, 8);
	e->p = e->z[0] + asize;
	e->cnt = calloc(asize, 8);
	e->b = ilog2(asize) + 1;
	e->r = 64;
	e->asize = asize;
	e->bbits = bbits;
	e->bmask = (1<<bbits) - 1;
	return e;
}

int rld_push(rldenc_t *e, int l, uint8_t c)
{
	int i, w;
	uint64_t x = rld_delta_enc1(l, &w) << e->b | c;
	w += e->b;
	if (w > e->r) {
		if (((e->p - e->z[e->n] + 1) & e->bmask) == 0) { // jump to the next block
			int y = (e->p - e->z[e->n]) & e->bmask;
			for (i = 0; i < e->asize; ++i)
				e->z[e->n][y + i] = e->cnt[i];
			if (e->p - e->z[e->n] + 1 == RLD_SUPBLK_SIZE) { // allocate a new superblock
				++e->n;
				e->z = realloc(e->z, (e->n + 1) * sizeof(void*));
				e->p = e->z[e->n] = calloc(RLD_SUPBLK_SIZE, 8);
			} else ++e->p;
			e->p += e->asize;
			e->r = 64 - w;
			*e->p |= x << e->r;
		} else {
			w -= e->r;
			*e->p++ |= x >> w;
			*e->p = x << (e->r = 64 - w);
		}
	} else e->r -= w, *e->p |= x << e->r;
	++e->cnt[c];
	return 0;
}

uint64_t rld_finish(rldenc_t *e)
{
	int i, y = (e->p - e->z[e->n]) & e->bmask;
	for (i = 0; i < e->asize; ++i)
		e->z[e->n][y + i] = e->cnt[i];
	return (((uint64_t)e->n * RLD_SUPBLK_SIZE) + (e->p - e->z[e->n])) * 64 + (64 - e->r);
}

int rld_dec_block(uint64_t *z, int bbits, int balpha, int asize, uint32_t *r) // FIXME: can be faster
{
	int i = 0, j, k, n = 1<<bbits, t = 0;
	uint64_t *p = z, x;
	while (i < n) {
		int y;
		if (i < n - 1) x = z[i] << t | (z[i+1] >> (64-t));
		else x = z[i] << t;
		for (j = 63; j >= 0; --j)
			if (x >> j) break;
		if (j < 0) break;
		y = ((63 - j)<<1) + 1;
	}
}

/*
int main(int argc, char *argv[])
{
	int w, x, z;
	if (argc > 1) {
		uint64_t y;
		z = atoi(argv[1]);
		x = rld_delta_enc1(z, &w);
		printf("%x, %d, %d, %d\n", x, w, w - (ilog2(x)+1), ilog2(z)+1);
		y = (uint64_t)x << (64 - w);
		printf("%d\n", rld_delta_dec1(y));
	}
	return 0;
}
*/
